# Generated by Django 2.2.2 on 2019-06-24 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, help_text='creation modify', null=True)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clubes',
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, help_text='creation modify', null=True)),
                ('id_ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dias',
                'db_table': 'dia',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='EstadoClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'EstadoClases',
                'db_table': 'estado_clase',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Generos',
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('es_limitrofe', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Posiciones',
                'db_table': 'posicion',
            },
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema Salud',
                'db_table': 'sistema_salud',
            },
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('es_delete', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('fecha_modi', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Tabla',
                'db_table': 'tabla',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Talleres',
                'db_table': 'taller',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, help_text='creation modify', null=True)),
                ('id_pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, help_text='creation modify', null=True)),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(max_length=255, unique=True)),
                ('valor_matricula', models.IntegerField()),
                ('valor_clase', models.IntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo', verbose_name='Periodo')),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dna', models.CharField(max_length=25, unique=True, verbose_name='Rut o Dna')),
                ('dv', models.CharField(max_length=2, verbose_name='Digito Verificador')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fceha de Nacimiento')),
                ('ocupacion', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('movil', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=20)),
                ('email_personal', models.EmailField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
                ('club_origen_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Club', verbose_name='Club Origen')),
                ('comuna_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Comuna', verbose_name='Comuna')),
                ('estado_civil_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.EstadoCivil', verbose_name='Estado Civil')),
                ('genero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Genero', verbose_name='Genero')),
                ('pais_origen_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pais', verbose_name='Nacionalidad')),
                ('posicion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Posicion', verbose_name='Posicion Estudiante')),
                ('sistema_salud_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.SistemaSalud', verbose_name='Sistema de Salud')),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Taller', verbose_name='Clase Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Gimnacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('fono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('numero_canchas', models.IntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
                ('comuna_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name_plural': 'Gimnacios',
                'db_table': 'gimnacio',
            },
        ),
        migrations.CreateModel(
            name='ClaseEnc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha Clase')),
                ('temario', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.CharField(default=main.models.get_default_my_hour, max_length=50)),
                ('hora_fin', models.CharField(default=main.models.get_default_my_hour, max_length=50)),
                ('numero_asistentes', models.IntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
                ('estado_clase_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.EstadoClase', verbose_name='Estado Clase')),
                ('gimnacio_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Gimnacio', verbose_name='Recinto')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Persona', verbose_name='Docente')),
            ],
            options={
                'verbose_name_plural': 'ClaseEncs',
                'db_table': 'clase_enc',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Provincia', verbose_name='Provincia'),
        ),
    ]
