# Generated by Django 2.2.2 on 2019-06-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_plan_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='id_region',
            new_name='region_id',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='id_pais',
            new_name='pais_id',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='id_ciudad',
        ),
        migrations.AddField(
            model_name='comuna',
            name='es_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Provincia', verbose_name='Provincia'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
