# Generated by Django 2.2.2 on 2019-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190624_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_titular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
