# Generated by Django 2.2.2 on 2019-06-25 22:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190625_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='es_titular',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='taller_id',
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('es_titular', models.BooleanField(default=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_delete', models.BooleanField(default=False)),
                ('fecha_crea', models.DateField(default=django.utils.timezone.now, help_text='creation date')),
                ('fecha_modi', models.DateField(auto_now=True, null=True)),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='equipo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Equipo', verbose_name='Equipo'),
            preserve_default=False,
        ),
    ]
