# Generated by Django 2.2.2 on 2019-07-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190625_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claseenc',
            old_name='estado_clase_id',
            new_name='estado_clase',
        ),
        migrations.RenameField(
            model_name='claseenc',
            old_name='gimnacio_id',
            new_name='gimnacio',
        ),
        migrations.RenameField(
            model_name='claseenc',
            old_name='profesor_id',
            new_name='profesor',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='provincia_id',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='taller_id',
            new_name='taller',
        ),
        migrations.RenameField(
            model_name='gimnacio',
            old_name='comuna_id',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='club_origen_id',
            new_name='club_origen',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='comuna_id',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='equipo_id',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='estado_civil_id',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='genero_id',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='pais_origen_id',
            new_name='pais_origen',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='posicion_id',
            new_name='posicion',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='sistema_salud_id',
            new_name='sistema_salud',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='taller_id',
            new_name='taller',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='pais_id',
            new_name='pais',
        ),
    ]
