# Generated by Django 2.2.2 on 2019-07-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190704_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='es_interno',
            field=models.BooleanField(default=True),
        ),
    ]
