# Generated by Django 2.2.3 on 2019-07-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_equipo_es_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='taller',
        ),
        migrations.AddField(
            model_name='equipo',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Club', verbose_name='Club'),
            preserve_default=False,
        ),
    ]
