# Generated by Django 2.2.3 on 2019-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_equipo_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_zurdo',
            field=models.BooleanField(default=False),
        ),
    ]
