# Generated by Django 2.2.3 on 2019-07-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_persona_es_zurdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
