# Generated by Django 2.2.3 on 2019-07-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190726_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
